### ISSUE TITLE
Pt distribution of phi

### ISSUE THREAD

**Issue by mvala** [mvala/alice-rsn-analysis#3]
```
root://alieos.saske.sk//eos/alike.saske.sk/alice/cern.ch/user/a/alitrain/PWGLF/LF_pp/389_20160307-1141/merge_runlist_4/AnalysisResults.root
```

pt 0.0-5.0 with step 0.5
phippData_100_phi_Unlike - phippData_100_phi_Mixing

**Comment by mvala** [comment]
Please do ```git pull```, because i fixed something now

**Comment by vrlakova** [comment]
my results - for pf 0.0- 5.0, step 5 bins
graph.pdf calculated on monday, March 14, older code
graph1.pdf calculated yesterday, March 15, new code. 
Comment: 1st point has no error on graph1, because error was too big ~ 10exp11, and 8th point too, error ~5.10exp5


[graph.pdf](https://github.com/mvala/alice-rsn-analysis/files/175647/graph.pdf)

[graph1.pdf](https://github.com/mvala/alice-rsn-analysis/files/175648/graph1.pdf)

**Comment by mvala** [comment]
You can do ```git pull```
